In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("dataset2.csv")
df.head(1)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15774727  Female   31            71000          0

In [5]:
df.isnull().any()

User ID            False
Gender             False
Age                False
EstimatedSalary    False
Purchased          False
dtype: bool

In [10]:
gender = pd.get_dummies(df["Gender"],drop_first=True)
gender.head(2)

Male
0     0
1     0

In [11]:
df.drop("User ID",axis=1,inplace=True)

In [12]:
df.head(2)

Gender  Age  EstimatedSalary  Purchased
0  Female   31            71000          0
1  Female   32           117000          1

In [13]:
df.drop("Gender",axis=1,inplace=True)

In [14]:
df = pd.concat([df,gender],axis=1)

In [15]:
df.head(2)

Age  EstimatedSalary  Purchased  Male
0   31            71000          0     0
1   32           117000          1     0

In [23]:
x = df.iloc[:,[0,1,3]].values
y = df.iloc[:,-2].values


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)



In [27]:
X_test[0]

array([   36, 54000,     0], dtype=int64)

In [28]:
X_train[0]

array([   47, 51000,     0], dtype=int64)

In [49]:
#feature scalling
import pickle

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

pickle.dump(sc,open("updated_scaler.pkl","wb"))



In [31]:
X_train[0]

array([ 0.36936322, -0.83101569, -0.93051258])

In [32]:
from sklearn.naive_bayes import GaussianNB
md = GaussianNB()



In [33]:
md.fit(X_train,y_train)

GaussianNB()

In [34]:
ypred = md.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
acc = accuracy_score(y_test,ypred)
acc*100

84.84848484848484

In [38]:
import pickle

pickle.dump(md,open("model.pkl","wb"))


In [45]:
#sv.transform([[47, 51000,0]])

array([[ 0.36936322, -0.83101569, -0.93051258]])